global:
  scrape_interval: 15s

  external_labels:
    monitor: 'zeek-demo'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']

  - job_name: 'zeek'
    scrape_interval: 5s
    static_configs:
      - targets: ['zeek:9911']
