---
repos:
- repo: https://github.com/adrienverge/yamllint.git
  rev: v1.29.0
  hooks:
    - id: yamllint

- repo: https://github.com/hadolint/hadolint
  rev: v2.12.0
  hooks:
    - id: hadolint

- repo: https://github.com/DavidAnson/markdownlint-cli2
  rev: v0.6.0
  hooks:
    - id: markdownlint-cli2
