apiVersion: 1

datasources:
  - name: Prometheus
    uid: "PBFA97CFB590B2093"
    type: prometheus
    # Access mode - proxy (server in the UI) or direct (browser in the UI).
    access: proxy
    url: http://prometheus:9090
    jsonData:
      httpMethod: POST

  - name: Loki
    uid: "P8E80F9AEF21F6940"
    type: loki
    # Access mode - proxy (server in the UI) or direct (browser in the UI).
    access: proxy
    url: http://loki:3100
    jsonData:
      httpMethod: POST
